import { Navbar } from '@/components/layout/navbar';
import { Footer } from '@/components/layout/footer';

export const metadata = {
  title: 'Terms of Service',
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="flex-1 container max-w-4xl mx-auto px-4 py-12 lg:py-24">
        <div className="prose prose-invert max-w-none">
          <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
          <p className="text-text-secondary mb-6">Last updated: May 2026</p>
          
          <h2 className="text-xl font-semibold mt-8 mb-4">1. Acceptance of Terms</h2>
          <p className="mb-4">By accessing and using OS_Gitfolio, you accept and agree to be bound by the terms and provision of this agreement.</p>

          <h2 className="text-xl font-semibold mt-8 mb-4">2. Use of GitHub Data</h2>
          <p className="mb-4">OS_Gitfolio is a visualization tool that relies on the public GitHub API. By using this service, you also agree to be bound by GitHub's Terms of Service and Privacy Policy. We only access data that is publicly available on your GitHub profile or data you explicitly grant us access to via OAuth.</p>

          <h2 className="text-xl font-semibold mt-8 mb-4">3. Disclaimer of Warranties</h2>
          <p className="mb-4">This service is provided "as is" and "as available" without any warranties of any kind, either express or implied. We do not guarantee the accuracy, completeness, or usefulness of any data generated by this tool.</p>

          <h2 className="text-xl font-semibold mt-8 mb-4">4. Limitation of Liability</h2>
          <p className="mb-4">In no event shall OS_Gitfolio be liable for any indirect, incidental, special, consequential or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, resulting from your use of the service.</p>
        </div>
      </main>
      <Footer />
    </>
  );
}
